# Generated by Django 4.2.6 on 2023-10-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='회사명')),
                ('address', models.CharField(max_length=200, verbose_name='주소')),
                ('nation', models.CharField(max_length=50, verbose_name='국가')),
                ('region', models.CharField(max_length=50, verbose_name='지역')),
            ],
        ),
    ]
