# Generated by Django 4.2.6 on 2023-10-14 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recuritment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50, verbose_name='채용포지션')),
                ('compensation', models.IntegerField(default=0, verbose_name='채용보상금')),
                ('contents', models.TextField(verbose_name='채용내용')),
                ('tech', models.CharField(max_length=100, verbose_name='사용기술')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
